# Generated by Django 5.2.6 on 2025-10-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('moderate_post', 'Can moderate posts')]},
        ),
    ]
